spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsb_schema?serverTimezone=Asia/Seoul
    username: TSB
    password: SUCCESS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        # show_sql: true
        "[format_sql]": true
        "[use_sql_comments]": true
        "[enable_lazy_load_no_trans]": true
        "[default_batch_fetch_size]": 100
        hbm2ddl:
          auto: create
        jdbc:
          "[batch_size]": 10
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type]": trace
